-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "public"."user" (
                        id SERIAL PRIMARY KEY,
                        email text NOT NULL,
                        refresh_token bytea NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_pkey ON "public"."user"(id int4_ops);


-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "public"."platform" (
                          id SERIAL PRIMARY KEY,
                          identifier text NOT NULL,
                          uuid uuid,
                          created_at timestamp without time zone NOT NULL,
                          updated_at timestamp without time zone NOT NULL,
                          "user" integer REFERENCES "public"."user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX platform_pkey ON "public"."platform" (id int4_ops);

