package tidal_v2

type SuccessResponse[T any, K any, V any] struct {
	Data     T `json:"data"`
	Included K `json:"included"`
	Links    V `json:"links"`
}

type LinksMeta struct {
	Description string `json:"description,omitempty"`
	NextCursor  string `json:"nextCursor"`
}

type Links struct {
	Meta LinksMeta `json:"meta"`
	Next string    `json:"next"`
	Self string    `json:"self"`
}

type AutoGenerated struct {
	Data struct {
		Attributes User   `json:"attributes"`
		ID         string `json:"id"`
		Type       string `json:"type"`
	} `json:"data"`
	Included []struct {
		Attributes struct {
			AccessType   string   `json:"accessType"`
			Availability []string `json:"availability"`
			BarcodeID    string   `json:"barcodeId"`
			Copyright    struct {
				Text string `json:"text"`
			} `json:"copyright"`
			Duration      string `json:"duration"`
			Explicit      bool   `json:"explicit"`
			ExternalLinks []struct {
				Href string `json:"href"`
				Meta struct {
					Type string `json:"type"`
				} `json:"meta"`
			} `json:"externalLinks"`
			MediaTags       []string `json:"mediaTags"`
			NumberOfItems   int      `json:"numberOfItems"`
			NumberOfVolumes int      `json:"numberOfVolumes"`
			Popularity      float64  `json:"popularity"`
			ReleaseDate     string   `json:"releaseDate"`
			Title           string   `json:"title"`
			Type            string   `json:"type"`
			Version         string   `json:"version"`
		} `json:"attributes"`
		ID            string `json:"id"`
		Relationships struct {
			Artists struct {
				Data []struct {
					ID   string `json:"id"`
					Type string `json:"type"`
				} `json:"data"`
				Links struct {
					Meta struct {
						NextCursor string `json:"nextCursor"`
					} `json:"meta"`
					Next string `json:"next"`
					Self string `json:"self"`
				} `json:"links"`
			} `json:"artists"`
			CoverArt struct {
				Data []struct {
					ID   string `json:"id"`
					Type string `json:"type"`
				} `json:"data"`
				Links struct {
					Meta struct {
						NextCursor string `json:"nextCursor"`
					} `json:"meta"`
					Next string `json:"next"`
					Self string `json:"self"`
				} `json:"links"`
			} `json:"coverArt"`
			Genres struct {
				Data []struct {
					ID   string `json:"id"`
					Type string `json:"type"`
				} `json:"data"`
				Links struct {
					Meta struct {
						NextCursor string `json:"nextCursor"`
					} `json:"meta"`
					Next string `json:"next"`
					Self string `json:"self"`
				} `json:"links"`
			} `json:"genres"`
			Items struct {
				Data []struct {
					ID   string `json:"id"`
					Meta struct {
						TrackNumber  int `json:"trackNumber"`
						VolumeNumber int `json:"volumeNumber"`
					} `json:"meta"`
					Type string `json:"type"`
				} `json:"data"`
				Included string `json:"included"`
				Links    struct {
					Meta struct {
						NextCursor string `json:"nextCursor"`
					} `json:"meta"`
					Next string `json:"next"`
					Self string `json:"self"`
				} `json:"links"`
			} `json:"items"`
			Owners struct {
				Data []struct {
					ID   string `json:"id"`
					Type string `json:"type"`
				} `json:"data"`
				Links struct {
					Meta struct {
						NextCursor string `json:"nextCursor"`
					} `json:"meta"`
					Next string `json:"next"`
					Self string `json:"self"`
				} `json:"links"`
			} `json:"owners"`
			Providers struct {
				Data []struct {
					ID   string `json:"id"`
					Type string `json:"type"`
				} `json:"data"`
				Links struct {
					Meta struct {
						NextCursor string `json:"nextCursor"`
					} `json:"meta"`
					Next string `json:"next"`
					Self string `json:"self"`
				} `json:"links"`
			} `json:"providers"`
			SimilarAlbums struct {
				Data []struct {
					ID   string `json:"id"`
					Type string `json:"type"`
				} `json:"data"`
				Links struct {
					Meta struct {
						NextCursor string `json:"nextCursor"`
					} `json:"meta"`
					Next string `json:"next"`
					Self string `json:"self"`
				} `json:"links"`
			} `json:"similarAlbums"`
			SuggestedCoverArts struct {
				Data []struct {
					ID   string `json:"id"`
					Meta struct {
						BackgroundColor string `json:"backgroundColor"`
						ForegroundColor string `json:"foregroundColor"`
					} `json:"meta"`
					Type string `json:"type"`
				} `json:"data"`
				Included string `json:"included"`
				Links    struct {
					Meta struct {
						NextCursor string `json:"nextCursor"`
					} `json:"meta"`
					Next string `json:"next"`
					Self string `json:"self"`
				} `json:"links"`
			} `json:"suggestedCoverArts"`
		} `json:"relationships,omitempty"`
		Type string `json:"type"`
	} `json:"included"`
	Links struct {
		Meta struct {
			NextCursor string `json:"nextCursor"`
		} `json:"meta"`
		Next string `json:"next"`
		Self string `json:"self"`
	} `json:"links"`
}
